# Multiples of 3 or 5
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

In [1]:
s = 0
for i in range(1000):
    if i%3==0 or i%5==0 :
        s += i
print(s)

233168

# Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [2]:
a = 1
b = 1
s = 0
while b < 4000000:
    if not b%2:
        s += b
    a, b = b, a+b
print(s)

4613732

# Sum square difference
<p>The sum of the squares of the first ten natural numbers is,</p>
$$1^2 + 2^2 + ... + 10^2 = 385$$
<p>The square of the sum of the first ten natural numbers is,</p>
$$(1 + 2 + ... + 10)^2 = 55^2 = 3025$$
<p>Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is $3025 - 385 = 2640$.</p>
<p>Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.</p>

In [3]:
print(int(sum(range(101))**2) - sum(map(lambda x: x**2, range(101))))

25164150

# Smallest multiple

2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

In [4]:
import math
math.lcm(*range(1,21))

232792560

# Numbers with a given prime factor sum
<p>Consider the numbers 15, 16 and 18:<br />
$15=3\times 5$ and $3+5=8$.<br />
$16 = 2\times 2\times 2\times 2$ and $2+2+2+2=8$.<br />
$18 = 2\times 3\times 3$ and $2+3+3=8$.<br /> 

15, 16 and 18 are the only numbers that have 8 as sum of the prime factors (counted with multiplicity).</p>
<p>
We define $S(k)$ to be the sum of all numbers $n$ where the sum of the prime factors (with multiplicity)  of $n$ is $k$.<br />
Hence $S(8) = 15+16+18 = 49$.<br />
Other examples: $S(1) = 0$, $S(2) = 2$, $S(3) = 3$, $S(5) = 5 + 6 = 11$.</p>
<p>
The Fibonacci sequence is $F_1 = 1, F_2 = 1, F_3 = 2, F_4 = 3, F_5 = 5$, ....<br />
Find the last nine digits of $\displaystyle\sum_{k=2}^{24}{S(F_k)}$.</p>

In [5]:
def factors(n):
    flist = []
    i = 2
    while i <= n:
        if not n%i:
            flist += [i]
            n = n//i
        else:
            i += 1
    return flist       

def s(k):
    n = 1
    ss = 0
    while n < 1:
        if sum(factors(n)) == k:
            ss += n
        n += 1
    return ss

def fib_iterative(n):
    new, old = 1, 0
    for i in range(n):
        new, old = old, new + old
    return old

sss = 0
for i in range(3, 26):
    sss += s(fib_iterative(i))
print(sss)

0

## Largest prime factor

The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143

In [6]:
max(factors(600851475143))

6857

## Largest palindrome product

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [7]:
def check_palindrome(num):
    line = str(num)

    def rvrs(line):
        if line:
            return line[-1] + rvrs(line[:-1])
        else:
            return line
    return line == rvrs(line)

list_pal = []
for i in range(100, 1000):
    for j in range(100, 1000):
        num = i*j
        if check_palindrome(num):
            list_pal.append(num)
print(max(list_pal))

906609

## Largest product in a series

The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832.

73167176531330624919225119674426574742355349194934
96983520312774506326239578318016984801869478851843
85861560789112949495459501737958331952853208805511
12540698747158523863050715693290963295227443043557
66896648950445244523161731856403098711121722383113
62229893423380308135336276614282806444486645238749
30358907296290491560440772390713810515859307960866
70172427121883998797908792274921901699720888093776
65727333001053367881220235421809751254540594752243
52584907711670556013604839586446706324415722155397
53697817977846174064955149290862569321978468622482
83972241375657056057490261407972968652414535100474
82166370484403199890008895243450658541227588666881
16427171479924442928230863465674813919123162824586
17866458359124566529476545682848912883142607690042
24219022671055626321111109370544217506941658960408
07198403850962455444362981230987879927244284909188
84580156166097919133875499200524063689912560717606
05886116467109405077541002256983155200055935729725
71636269561882670428252483600823257530420752963450

Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?

In [8]:
line = str(7316717653133062491922511967442657474235534919493496983520312774506326239578318016984801869478851843858615607891129494954595017379583319528532088055111254069874715852386305071569329096329522744304355766896648950445244523161731856403098711121722383113622298934233803081353362766142828064444866452387493035890729629049156044077239071381051585930796086670172427121883998797908792274921901699720888093776657273330010533678812202354218097512545405947522435258490771167055601360483958644670632441572215539753697817977846174064955149290862569321978468622482839722413756570560574902614079729686524145351004748216637048440319989000889524345065854122758866688116427171479924442928230863465674813919123162824586178664583591245665294765456828489128831426076900422421902267105562632111110937054421750694165896040807198403850962455444362981230987879927244284909188845801561660979191338754992005240636899125607176060588611646710940507754100225698315520005593572972571636269561882670428252483600823257530420752963450)

In [9]:
list_prod = []
for i in range(13, 1001):
    tmp = 1
    for j in range(13):
        tmp *= int(line[i-13:i][j])
    list_prod.append(tmp)
print(max(list_prod))

23514624000

## Longest Collatz sequence

<p>The following iterative sequence is defined for the set of positive integers:</p>
<p class="margin_left"><var>n</var> → <var>n</var>/2 (<var>n</var> is even)<br /><var>n</var> → 3<var>n</var> + 1 (<var>n</var> is odd)</p>
<p>Using the rule above and starting with 13, we generate the following sequence:</p>
<div class="center">13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1</div>
<p>It can be seen that this sequence (starting at 13 and finishing at 1) contains 10 terms. Although it has not been proved yet (Collatz Problem), it is thought that all starting numbers finish at 1.</p>
<p>Which starting number, under one million, produces the longest chain?</p>
<p class="note"><b>NOTE:</b> Once the chain starts the terms are allowed to go above one million.</p>

In [10]:
def collatz(n):
    seq=[]
    seq.append(n)
    while n != 1:
        if n % 2 == 0:
            n = n//2
            seq.append(n)
        else:
            n = n*3 + 1
            seq.append(n)
    return seq

lenlist = []
for i in range(1, 1000000):
    lenlist.append(len(collatz(i)))
    
num = max(lenlist)
lenlist.index(num) + 1

837799

## Maximum path sum I

<p>By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.</p>
<p class="monospace center"><span class="red"><b>3</b></span><br /><span class="red"><b>7</b></span> 4<br />
2 <span class="red"><b>4</b></span> 6<br />
8 5 <span class="red"><b>9</b></span> 3</p>
<p>That is, 3 + 7 + 4 + 9 = 23.</p>
<p>Find the maximum total from top to bottom of the triangle below:</p>
<p class="monospace center">75<br />
95 64<br />
17 47 82<br />
18 35 87 10<br />
20 04 82 47 65<br />
19 01 23 75 03 34<br />
88 02 77 73 07 63 67<br />
99 65 04 28 06 16 70 92<br />
41 41 26 56 83 40 80 70 33<br />
41 48 72 33 47 32 37 16 94 29<br />
53 71 44 65 25 43 91 52 97 51 14<br />
70 11 33 28 77 73 17 78 39 68 17 57<br />
91 71 52 38 17 14 91 43 58 50 27 29 48<br />
63 66 04 68 89 53 67 30 73 16 69 87 40 31<br />
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23</p>
<p class="note"><b>NOTE:</b> As there are only 16384 routes, it is possible to solve this problem by trying every route. However, <a href="problem=67">Problem 67</a>, is the same challenge with a triangle containing one-hundred rows; it cannot be solved by brute force, and requires a clever method! ;o)</p>

In [2]:
triangle = [
[75],
[95, 64],
[17, 47, 82],
[18, 35, 87, 10],
[20, 4, 82, 47, 65],
[19, 1, 23, 75, 3, 34],
[88, 2, 77, 73, 7, 63, 67],
[99, 65, 4, 28, 6, 16, 70, 92],
[41, 41, 26, 56, 83, 40, 80, 70, 33],
[41, 48, 72, 33, 47, 32, 37, 16, 94, 29],
[53, 71, 44, 65, 25, 43, 91, 52, 97, 51, 14],
[70, 11, 33, 28, 77, 73, 17, 78, 39, 68, 17, 57],
[91, 71, 52, 38, 17, 14, 91, 43, 58, 50, 27, 29, 48],
[63, 66, 4, 68, 89, 53, 67, 30, 73, 16, 69, 87, 40, 31],
[4, 62, 98, 27, 23, 9, 70, 98, 73, 93, 38, 53, 60, 4, 23],
]

In [4]:
rows = len(triangle)

for i in range(rows-2, -1, -1):
    for j in range(len(triangle[i])):
        triangle[i][j]+=max(triangle[i+1][j], triangle[i+1][j+1])
triangle[0][0]

1074

## Maximum path sum II

<p>By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.</p>
<p class="monospace center"><span class="red"><b>3</b></span><br /><span class="red"><b>7</b></span> 4<br />
2 <span class="red"><b>4</b></span> 6<br />
8 5 <span class="red"><b>9</b></span> 3</p>
<p>That is, 3 + 7 + 4 + 9 = 23.</p>
<p>Find the maximum total from top to bottom in <a href="project/resources/p067_triangle.txt">triangle.txt</a> (right click and 'Save Link/Target As...'), a 15K text file containing a triangle with one-hundred rows.</p>
<p class="smaller"><b>NOTE:</b> This is a much more difficult version of <a href="problem=18">Problem 18</a>. It is not possible to try every route to solve this problem, as there are 2<sup>99</sup> altogether! If you could check one trillion (10<sup>12</sup>) routes every second it would take over twenty billion years to check them all. There is an efficient algorithm to solve it. ;o)</p>

In [16]:
f = open("triangle.txt", "r", encoding="utf-8")
text = f.read()
f.close()   

text = text.split("\n")[:-1]
triangle = []
for line in text:
    line = line.split(" ")
    line = [int(x) for x in line]
    triangle.append(line)

rows = len(triangle)

for i in range(rows-2, -1, -1):
    for j in range(len(triangle[i])):
        triangle[i][j]+=max(triangle[i+1][j], triangle[i+1][j+1])
triangle[0][0]

7273

## Pandigital prime

We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once. For example, 2143 is a 4-digit pandigital and is also prime.

What is the largest n-digit pandigital prime that exists?

In [13]:
def is_pandigital(n, s=9): 
    n=str(n)
    return len(n)==s and not '1234567890'[:s].strip(n)

def is_prime(n):
    if n <= 1: return False
    if n <= 3: return True
    if n%2==0 or n%3 == 0: return False
    r = int(n**0.5)
    f = 5
    while f <= r:
        if n%f == 0 or n%(f+2) == 0: return False
        f+= 6
    return True

In [14]:
for i in range(7654321, 1234568, -1):
    if is_pandigital(i, 7) and is_prime(i):
        print(i)
        break

7652413

## Digit cancelling fractions
<p>The fraction <sup>49</sup>/<sub>98</sub> is a curious fraction, as an inexperienced mathematician in attempting to simplify it may incorrectly believe that <sup>49</sup>/<sub>98</sub> = <sup>4</sup>/<sub>8</sub>, which is correct, is obtained by cancelling the 9s.</p>
<p>We shall consider fractions like, <sup>30</sup>/<sub>50</sub> = <sup>3</sup>/<sub>5</sub>, to be trivial examples.</p>
<p>There are exactly four non-trivial examples of this type of fraction, less than one in value, and containing two digits in the numerator and denominator.</p>
<p>If the product of these four fractions is given in its lowest common terms, find the value of the denominator.</p>

In [15]:
for i in range(11, 100):
    for j in range(11, 100):
        if i/j < 1 and len(set(str(i)+str(j)))<4 and len(set(str(i)))==2 and len(set(str(j)))==2:
            ch = str(set(str(i))&set(str(j)))[2]
            ni = int(str(i).replace(ch, "",1))
            nj = int(str(j).replace(ch, "",1))
            if ch != "0" and nj != 0 and i/j == ni/nj:
                print(i,j)

16 64
19 95
26 65
49 98

In [16]:
4*5*5*1

100

## Triangular, pentagonal, and hexagonal

<p>Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:</p>
<table><tr><td>Triangle</td>
<td> </td>
<td>T<sub><i>n</i></sub>=<i>n</i>(<i>n</i>+1)/2</td>
<td> </td>
<td>1, 3, 6, 10, 15, ...</td>
</tr><tr><td>Pentagonal</td>
<td> </td>
<td>P<sub><i>n</i></sub>=<i>n</i>(3<i>n</i>−1)/2</td>
<td> </td>
<td>1, 5, 12, 22, 35, ...</td>
</tr><tr><td>Hexagonal</td>
<td> </td>
<td>H<sub><i>n</i></sub>=<i>n</i>(2<i>n</i>−1)</td>
<td> </td>
<td>1, 6, 15, 28, 45, ...</td>
</tr></table><p>It can be verified that T<sub>285</sub> = P<sub>165</sub> = H<sub>143</sub> = 40755.</p>
<p>Find the next triangle number that is also pentagonal and hexagonal.</p>

In [42]:
tr = set()
pn = set()
hx = set()
n = 2
while True:
    tr.add((n*(n+1))//2)
    pn.add((n*(3*n-1))//2)
    hx.add(n*(2*n-1))
    x = tr & pn & hx 
    if len(x) == 2:
        print(x)
        break
    else:
        n+=1

{40755, 1533776805}